"""Initial migration.

Revision ID: 04733375b1d2
Revises: 
Create Date: 2022-01-13 10:54:23.495645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04733375b1d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('department_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('department_name', sa.String(), nullable=True),
    sa.Column('department_phone_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_table('employee',
    sa.Column('employee_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('department_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('department')
    # ### end Alembic commands ###
